name: Bug report
description: Create a report to help us improve
title: ""
labels: []
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ## Create a report to help us improve
        Please fill out the details below so we can reproduce and resolve the issue.

  - type: textarea
    id: describe
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: To Reproduce
      description: Steps to reproduce the behavior.
      value: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem.

  - type: textarea
    id: desktop
    attributes:
      label: Desktop (please complete the following information)
      value: |
        - OS: [e.g. iOS]
        - Browser [e.g. chrome, safari]
        - Version [e.g. 22]

  - type: textarea
    id: smartphone
    attributes:
      label: Smartphone (please complete the following information)
      value: |
        - Device: [e.g. iPhone6]
        - OS: [e.g. iOS8.1]
        - Browser [e.g. stock browser, safari]
        - Version [e.g. 22]

  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Add any other context about the problem here.

  - type: dropdown
    id: layer
    attributes:
      label: Affected layer (optional)
      description: Select the most relevant repository area.
      options:
        - schemas/
        - pdl/
        - generator/
        - cli/
        - reproducibility/
        - modules/
        - docs/
        - Other

  - type: checkboxes
    id: phases
    attributes:
      label: Affected phase(s) (optional)
      description: Choose any pipeline phases impacted.
      options:
        - label: ingest
        - label: normalize
        - label: parse
        - label: analyze
        - label: generate
        - label: validate
        - label: compare
        - label: interpret
        - label: log

  - type: markdown
    attributes:
      value: |
        **Optional additional items**

  - type: input
    id: issue_default_title
    attributes:
      label: Issue default title

  - type: input
    id: assignees
    attributes:
      label: Assignees

  - type: input
    id: labels
    attributes:
      label: Labels
