name: Feature request
description: Propose an improvement aligned with sswg-mvm principles
title: "[FEATURE] "
labels: ["enhancement"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ## Feature request

        Use this form to propose **new capabilities or improvements**.
        Requests should align with the sswg/mvm 9-phase pipeline, determinism rules, and validation gates.

  - type: textarea
    id: feature_description
    attributes:
      label: Feature description
      description: Clearly describe the proposed feature or improvement.
      placeholder: What should be added or changed?
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: Motivation / problem statement
      description: Explain the problem this feature solves or why it is needed.
    validations:
      required: true

  - type: textarea
    id: proposed_approach
    attributes:
      label: Proposed approach
      description: Describe a possible implementation approach or design.
    validations:
      required: true

  - type: dropdown
    id: affected_layer
    attributes:
      label: Affected repository layer
      description: Select the primary layer impacted.
      options:
        - schemas/
        - pdl/
        - generator/
        - cli/
        - reproducibility/
        - modules/
        - docs/
        - Other

  - type: checkboxes
    id: affected_phases
    attributes:
      label: Affected pipeline phase(s)
      description: Select all phases this feature would impact.
      options:
        - label: ingest
        - label: normalize
        - label: parse
        - label: analyze
        - label: generate
        - label: validate
        - label: compare
        - label: interpret
        - label: log

  - type: textarea
    id: determinism_considerations
    attributes:
      label: Determinism and validation considerations
      description: Describe any expected impact on deterministic phases, schemas, or validation gates.

  - type: textarea
    id: additional_context
    attributes:
      label: Additional context
      description: Add any other relevant information, links, or references.
